### ISSUE TITLE
[suggestion] possible performance improvement

### ISSUE THREAD

**Issue by gabriel-andreescu** [anegostudios/vsmoddb#11]
hi,
while working on #10 I've noticed that `moddb.release.modid` doesn't have an index, and it's used to query all the mods on https://github.com/anegostudios/vsmoddb/blob/master/api.php#L323

this was based on tables.sql (maybe the current schema has an index)

another idea (which I think is even better long term) is to remove `modidstr`'s completely from `/api/mods` endpoint, this way there is no need to GROUP BY, and an offset/page parameter can be used to paginate the response when there will be millions of mods.

**Comment by tyronx** [comment]
[api.php:264](https://github.com/anegostudios/vsmoddb/blob/master/api.php#L264) redirects to an if statement.

**Comment by gabriel-andreescu** [comment]
yeah, the code changed since I posted this: https://github.com/anegostudios/vsmoddb/blob/master/api.php#L323

**Comment by tyronx** [comment]
ah i see. thanks for the suggestion. I have added an index there now
