### ISSUE TITLE
[Suggestion] Mod dependencies

### ISSUE THREAD

**Issue by zsuatem** [anegostudios/vsmoddb#13]
Some mods require others to work.
Add the ability to set for a given version of a mod the required dependencies.
Add the ability to download these dependencies via API.

It would be good if the version of the required mod could be specified in detail.
For example (like npm)
1.0.4 - specific version
~1.0.4 - any patch version >= 1.0.4
^1.0.4 - any minor version >= 1.0.4
>=1.0.4 - >= any major version >= 1.0.4

**Comment by tyronx** [comment]
There is suppot for dependency requirements, see also https://wiki.vintagestory.at/index.php/Modinfo

As of 1.18 the game will also offer to download unmet dependencies.

**Comment by zsuatem** [comment]
That's cool, but I think it would be useful if these dependencies were also shown in the mod database.  If someone wants to download mods from the site and not through the game would have an easier task and mod creators would not have to additionally provide such information.

**Comment by tyronx** [comment]
As mentioned, as of 1.18 this info is not really needed anymore.
